### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by onurhan1337** [sommd/rustmap#2]
When I type the command `rustmap xxx.xx.xxx.xxx` on Ubuntu, I get the error "**_No such file or directory (os error 2)_**". How can I solve it?

**Comment by sommd** [comment]
I'm assuming you've installed it using `cargo install`? In that case, it installs it to `~/.cargo/bin/rustmap` by default, so you can run `~/.cargo/bin/rustmap xxx.xxx.xxx.xxx` to run it. If you want to just run it as `rustmap ...`, then you'll need to add `~/.cargo/bin` to your `PATH` variable: https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path

**Comment by onurhan1337** [comment]
My fault, sorry. 
As you mentioned, I installed it with the `cargo install` command, but I got an error because I didn't add it to my PATH! Thanks for the info mate.
